# Generated by Django 4.1.7 on 2023-03-15 08:25

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TK', 'Tanks'), ('HR', 'Healers'), ('DD', 'Damage dealers'), ('TR', 'Traders'), ('GM', 'Guild masters'), ('QG', 'Quest givers'), ('ST', 'Smiths'), ('TR', 'Tanners'), ('PN', 'Potions'), ('SM', 'Spell masters')], default='TK', max_length=2)),
                ('datetime_of_creation', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=127)),
                ('text_upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_creation', models.DateTimeField(auto_now_add=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('condition', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.sticker')),
            ],
        ),
    ]
