# Generated by Django 4.1.7 on 2023-03-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Tanks'), ('Healers', 'Healers'), ('Damage dealers', 'Damage dealers'), ('Traders', 'Traders'), ('Guild masters', 'Guild masters'), ('Quest givers', 'Quest givers'), ('Smiths', 'Smiths'), ('Tanners', 'Tanners'), ('Potions', 'Potions'), ('Spell masters', 'Spell masters')], default='Tanks', max_length=14),
        ),
    ]
